apiVersion: apps/v1
kind: Deployment
metadata:
  name: uofthacks12-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uofthacks12-backend
  template:
    metadata:
      labels:
        app: uofthacks12-backend
    spec:
      containers:
      - name: uofthacks12-backend
        image: codejediondockerhub/uofthacks12-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: MONGODB_URI
              key: MONGODB_URI
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: PINECONE_API_KEY
              key: PINECONE_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: OPENAI_API_KEY
              key: OPENAI_API_KEY