name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: List files in workspace
      run: ls -la
      
    - name: Print directory contents
      run: ls -R
      
    - name: Check for DOCKERFILE
      run: |
        if [ -f "DOCKERFILE" ]; then
          echo "DOCKERFILE found"
        else
          echo "DOCKERFILE not found"
          ls -la
          exit 1
        fi
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: codejediondockerhub
        password: ${{ secrets.DOCKER_PAT }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./DOCKERFILE
        push: true
        tags: codejediondockerhub/uofthacks12-backend:latest
